version: "3"
services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: ${PROXY_CONTAINER_NAME}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ${CERTS_DIR}:/etc/nginx/certs:ro
    restart: always
    logging:
      options:
        max-size: "5m"
        max-file: "10"
  web:
    image: nginx
    container_name: ${WEB_CONTAINER_NAME}
    environment:
      VIRTUAL_HOST: ${HOSTNAME}
      CERT_NAME: ${CERTS_FILE_NAME}
      HTTPS_METHOD: noredirect
    volumes:
      - ${WEB_DOCUMENT_ROOT}:/usr/share/nginx/html
      - ${WEB_CONF_DIR}:/etc/nginx/conf.d
    restart: always
  smtp:
    image: schickling/mailcatcher
    container_name: ${MAIL_CATCHER_CONTAINER_NAME}
    ports:
      - 1080:1080
      - 1025:1025
    restart: always
networks:
  default:
    external:
      name: ${PROXY_NETWORK_NAME}
